import { createApp } from 'vue';
import App from './App.vue';
import './registerServiceWorker';
import router from './router';
import store from './store';
import AdminComponents from './admin/components/index';
// import { KRow } from './admin/components/index';
const app = createApp(App);
app.use(AdminComponents);
// app.use(KRow);
app.use(store).use(router).mount('#app');
