// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
}
export {}
